In [50]:
#Import required libraries
import os
import pandas as pd
from shutil import copyfile
!python --version

Python 3.5.4 :: Anaconda, Inc.

# Gather the Data

### User Input

In [67]:
#Which dataset is to be used for analysis?
dataset = 'fwwc19'

### End User Input

###### In order to use this for future projects I have created a variable for my global dataset location and a variable for dataset to easily access the data I want

In [66]:
#My datasets are saved in a global folder called "datasets"
datasets_location = '../datasets'

#Get a list of the .csv files available for the selected dataset 
data_files = [f for f in os.listdir(os.path.join(datasets_location,dataset)) if f.endswith('.csv')]

#Print the .csv file names, as if there is more than one it is useful to know that merge/join/concat may need to be used
print("Data files found:\n",data_files)

#Check if file exists in project folder, if not, copy it here
if not os.path.exists(str(data_files[0])):
    copyfile(os.path.join(datasets_location,dataset,data_files[0]), os.path.join(os.getcwd(),data_files[0]))

#Create the dataframe from the imported data
df = pd.read_csv(data_files[0])

Data files found:
 ['Womens_World_Cup_2019.csv']

In [68]:
#----IF MULTIPLE FILES
#In this instance there is only one file, but if there were more it would be beneficial to
#create a dictionary with the format {data_file, data_file_path} so that they could be looped if required to read/join

#Something like...
# for i in len(data_files):
#     data_files_paths = dict.fromkeys("testasdf" , os.path.join(datasets_location,dataset,str(data_files[i])))

#It would also be necessary to loop the command  that creates the df, or use something different
#----

In [69]:
#In order to inspect what data is available, I want to make sure to be able to visualise all the columns
pd.set_option('display.max_columns', None)

df.head()

,Year,Team 1,Score 1,Team 2,Score 2,Round,Date,Penalty Kicks,Penalty Score 1,Penalty Score 2,Player of the Match 1,Player of the Match 2,Total Shots 1,Total Shots 2,Shots on Goal 1,Shots on Goal 2,Shots Blocked 1,Shots Blocked 2,Fouls 1,Fouls 2,Corner Kicks 1,Corner Kicks 2,Possession 1,Possession 2
0,2019,FRA,4,KOR,0,Group,7-Jun,0,NaN,NaN,1,0,21,4,8,1,5,1,11,11,13,1,60,40
1,2019,GER,1,CHN,0,Group,8-Jun,0,NaN,NaN,1,0,18,4,5,1,5,1,7,19,8,3,62,38
2,2019,ESP,3,RSA,1,Group,8-Jun,0,NaN,NaN,1,0,25,4,12,2,8,2,12,13,5,2,72,28
3,2019,NOR,3,NGA,0,Group,8-Jun,0,NaN,NaN,1,0,10,9,4,1,2,2,5,10,5,5,57,43
4,2019,AUS,1,ITA,2,Group,9-Jun,0,NaN,NaN,0,1,17,5,7,3,3,1,20,19,6,3,57,43

In [70]:
#This is a relatively small dataset, but more columns would be more difficult to inspect
#It is possible to inspect the columns in the dataset in a more "textual way"
df.columns

Index(['Year', 'Team 1', 'Score 1', 'Team 2', 'Score 2', 'Round', 'Date',
       'Penalty Kicks', 'Penalty Score 1', 'Penalty Score 2',
       'Player of the Match 1', 'Player of the Match 2', 'Total Shots 1',
       'Total Shots 2', 'Shots on Goal 1', 'Shots on Goal 2',
       'Shots Blocked 1', 'Shots Blocked 2', 'Fouls 1', 'Fouls 2',
       'Corner Kicks 1', 'Corner Kicks 2', 'Possession 1', 'Possession 2'],
      dtype='object')

# Assess The Data

In [71]:
#Before deciding on what I want to know from the data, I want to understand the quality of the data
df.describe()

,Year,Score 1,Score 2,Penalty Kicks,Penalty Score 1,Penalty Score 2,Player of the Match 1,Player of the Match 2,Total Shots 1,Total Shots 2,Shots on Goal 1,Shots on Goal 2,Shots Blocked 1,Shots Blocked 2,Fouls 1,Fouls 2,Corner Kicks 1,Corner Kicks 2,Possession 1,Possession 2
count,52.0,52.000000,52.000000,52.000000,1.0,1.0,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,2019.0,1.653846,1.153846,0.019231,4.0,1.0,0.557692,0.442308,13.634615,11.557692,4.961538,3.884615,3.192308,2.673077,9.846154,10.173077,4.826923,4.365385,51.134615,48.134615
std,0.0,2.018392,1.194507,0.138675,NaN,NaN,0.501506,0.501506,7.928674,6.601882,3.709878,2.609589,2.401294,2.083748,3.852092,4.626103,3.750666,2.897117,12.120359,10.219222
min,2019.0,0.000000,0.000000,0.000000,4.0,1.0,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,4.000000,25.000000
25%,2019.0,0.000000,0.000000,0.000000,4.0,1.0,0.000000,0.000000,7.000000,7.500000,2.750000,2.000000,1.000000,1.000000,7.000000,7.000000,2.000000,2.000000,44.500000,40.750000
50%,2019.0,1.000000,1.000000,0.000000,4.0,1.0,1.000000,0.000000,12.000000,11.500000,4.000000,3.000000,3.000000,2.000000,10.000000,9.000000,4.000000,4.000000,50.500000,49.500000
75%,2019.0,2.000000,2.000000,0.000000,4.0,1.0,1.000000,1.000000,18.000000,15.250000,6.250000,6.000000,4.250000,4.000000,12.250000,12.000000,7.000000,6.250000,59.250000,55.500000
max,2019.0,13.000000,5.000000,1.000000,4.0,1.0,1.000000,1.000000,39.000000,29.000000,21.000000,12.000000,9.000000,8.000000,20.000000,24.000000,15.000000,12.000000,75.000000,69.000000

In [72]:
#Check if there are any missing data points
df.columns.isna()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

###### <font color=red>None of the columns have any NaN and so do not need to be removed, dropped or imputed. Given the data is for football matches, if data was missing for any given match for only one team, it would be necessary to remove the data since imputing would an incorrect representation of what happened in reality (e.g. we don't know if the team won, lost or drew). The same would be for a single match where data was missing from both teams.</font>

In [43]:
#Some useful things to store
num_rows = df.shape[0]
num_columns = df.shape[1]
print('Rows = {}'.format(num_rows))
print('Columns = {}'.format(num_columns))

#Note that I could use f-strings here but I am running python3.5 not python3.6 or higher
# print(f"Columns = {num_columns}")

Rows = 52
Columns = 24